# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 09:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='threshold',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.9)]),
        ),
    ]
